site_name: docs.ruan.dev
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.expand

repo_url: https://github.com/ruanbekker/docs-ruan-dev/
site_url: https://docs.ruan.dev
edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: ¶

nav:
  - Home: index.md
  - Setup:
      - Quick start: quick-start.md
  - Cheatsheets:
      - AWS-CLI: cheatsheets/awscli.md
      - Elasticsearch: cheatsheets/elasticsearch.md
  - Docker:
      - Logging with Docker: docker/logging.md
      - Flask and Redis: docker/flask-redis.md
      - Minio: docker/minio.md
      - Go Multistage Builds: docker/multistage-go-app.md
      - Traefik: docker/traefik.md
      - MySQL with PhpMyAdmin: docker/mysql-phpmyadmin.md
      - PHP Nginx and MySQL: docker/php-nginx-mysql.php
      - Loki: docker/loki.md
  - Kubernetes:
      - k3s: kubernetes/k3s.md

copyright: Copyright &copy; 2017 - 2021 <a href="https://twitter.com/ruanbekker">Ruan Bekker</a> | <a href="https://github.com/ruanbekker/mkdocs-material-starter/blob/main/LICENSE">Documentation Distributed under MIT License</a>
